.TH tspreed 1 2021-03-05 tspreed

.SH NAME
tspreed \- terminal RSVP speed reader with Spritz-like functionality

.SH SYNOPSIS
.B tspreed
[\fB\-lqhifbv\fR]
[\fB\-w\fR \fIwpm\fR]
[\fB\-n\fR \fInum\fR]
[\fB\-p\fR \fIstyle\fR]
[\fB\-c\fR \fIcolor\fR]

.SH DESCRIPTION
\fBtspreed\fR is a terminal RSVP speed reader with Spritz-like functionality written in POSIX shell. It reads plain text from stdin and presents it one word at time.

If tspreed is terminated before the presentation has finished, the progress of the presentation is passed to stdout.

.SH OPTIONS
.TP
.B -w \fIwpm\fR
Speed words are presented at in WPM (words per minute). Required to be set. Minimum value of \fI1\fR, maximum value of \fI60000\fR.
.TP
.B -n \fInum\fR 
Start presenting from the \fIn\fRth word. Minimum value of \fI1\fR.
.TP
.B -l
Vary the speed words are presented at based on their length.
.TP
.B -q
Do not pass presentation progress to stdout if tspreed is terminated before the presentation has finished.
.TP
.B -h
Hide the cursor during the presentation.
.TP
.B -i
Display progress information during the presentation.
.TP
.B -f
Highlight the focus letter (also known as the pivot or optimal recognition point) of the word being presented.
.TP
.B -p \fIstyle\fR
Display pointers in a given style pointing towards the focus letter. Only takes effect if focus letter highlighting is enabled. Styles: \fInone\fR, \fIline\fR, \fIpoint\fR.
.TP
.B -b
Display the focus letter in bold. Only takes effect if focus letter highlighting is enabled.
.TP
.B -c \fIcolor\fR
Display the focus letter in a given color. Only takes effect if focus letter highlighting is enabled. Values are ANSI X3.64 color values, ranging from \fI0\fR to \fI255\fR. Note that color values above \fI7\fR mostly only work on featured terminal emulators i.e. xterm.
.TP
.B -v
Print tspreed version and exit.

.SH CONFIGURATION
The values provided in the command options take precedence over the values of the user-specific config file, which takes precedence over the values of the system-wide config file.
.TP
.B wpm=\fIwpm\fR
Equivalent to \fB-w\fR option.
.TP
.B numstart=\fInum\fR
Equivalent to \fB-n\fR option.
.TP
.B lengthvary=\fIbool\fR
Equivalent to \fB-l\fR option.
.TP
.B quietexit=\fIbool\fR
Equivalent to \fB-q\fR option.
.TP
.B hidecursor=\fIbool\fR
Equivalent to \fB-h\fR option.
.TP
.B proginfo=\fIbool\fR
Equivalent to \fB-i\fR option.
.TP
.B focus=\fIbool\fR
Equivalent to \fB-f\fR option.
.TP
.B focuspointer=\fIstyle\fR
Equivalent to \fB-p\fR option.
.TP
.B focusbold=\fIbool\fR
Equivalent to \fB-b\fR option.
.TP
.B focuscolor=\fIcolor\fR
Equivalent to \fB-c\fR option.

.SH EXIT STATUS
.TP
.B 0
Success.
.TP
.B 1
Failure due to incorrect options/configuration.
.TP
.B 2
Failure due to system not supporting required functionalities that are not POSIX-compliant.
.TP
.B 3
Failure due to terminal/terminal emulator not supporting required capabilities.
.TP
.B 8
Presentation terminated before completion - no failure.

.SH ENVIRONMENT
.TP
.B XDG_CONFIG_HOME
User-specific configuration is located within the directory defined. If \fB$XDG_CONFIG_HOME\fR is empty or not set, then \f(BI$HOME\fI/.config\fR is used in its place. This is in accordance with the XDG Base Directory Specification as defined by freedesktop.org.

.SH FILES
.TP
.I /etc/tspreed/tspreed.rc
Global configuration file.
.TP
.I \f(BI$XDG_CONFIG_HOME\fI/tspreed/tspreed.rc
Local configuration file.

.SH EXAMPLES
.P
$ \fBtspreed < textfile\fR
.P
$ \fBpdftotext document.pdf - | tspreed -w 300 -n 120 -lifb -p line -c 1\fR

.SH PORTABILITY 
\fBtspreed\fR 'officially' supports GNU-based systems and BSD-based systems only (i.e. GNU/Linux, macOS, BSD). This does not mean the script will not work on other Unix-like systems or portability is not treated as a priority, however this does mean compatibility is not guaranteed on unsupported systems.

The script utilizes terminal capabilities via \fBtput\fR(1) that are often supported by terminals/terminal emulators that support \fIANSI X3.64\fR escape codes (which have been well-supported since the 1980s) where possible. Note that while the capabilities utilized are often well supported, no standard can guarentee their support across terminals/terminal emulators. The script will determine at runtime which capabilities the terminal supports and either exit with an error or adjust its behavior accordingly.

.SH PORTABILITY - POSIX
\fBtspreed\fR attempts to adhere to \fIIEEE Std 1003.1-2001\fR (a.k.a. \fISUSv3\fR or \fIPOSIX.1-2001\fR) in order to be portable across Unix-like systems. However, non-compliant functionalities have been utilized to either overcome limitations of the standard or improve performance where possible. The script will determine at runtime which non-compliant functionalities the system supports and either exit with an error or adjust its behavior accordingly.

The script must utilize at least one of the non-compliant functionalities listed below. The script will exit with an error if neither functionality is supported by the system.
.TP
The '%N' format in \fBdate\fR(1).
.TP
The use of floating point values for the time operand in \fBsleep\fR(1).
.P

.SH REPORTING BUGS
Bugs and issues can be reported on GitHub or GitLab.

<https://github.com/n-ivkovic/tspreed/issues>

<https://gitlab.com/n-ivkovic/tspreed/issues>

.SH AUTHORS
Nicholas Ivkovic <nivkovic@tuta.io>.

.SH COPYRIGHT
Copyright (c) 2021 Nicholas Ivkovic.

Licensed under the GNU General Public License version 3 or later. See ./LICENSE, or <https://gnu.org/licenses/gpl.html> if more recent, for details.

This is free software: you are free to change and redistribute it. There is NO WARRANTY, to the extent permitted by law.
