.TH tspreed 1 2021-12-01 tspreed

.SH NAME
tspreed \- terminal RSVP speed reader with Spritz-like functionality

.SH SYNOPSIS
.B tspreed
[\fB\-lqhifbv\fR]
[\fB\-w\fR \fIwpm\fR]
[\fB\-n\fR \fInum\fR]
[\fB\-s\fR \fIchars\fR]
[\fB\-p\fR \fIstyle\fR]
[\fB\-c\fR \fIcolor\fR]

.SH DESCRIPTION
\fBtspreed\fR is a terminal RSVP speed reader with Spritz-like functionality written in POSIX-compliant shell. It reads plain text from stdin and presents it one word at time.

If tspreed is terminated before the presentation has finished, the progress of the presentation is passed to stdout.

.SH OPTIONS
.TP
.B -w \fIwpm\fR
Speed words are presented at in WPM (words per minute). Required to be set. Minimum value of \fI1\fR, maximum value of \fI60000\fR.
.TP
.B -n \fInum\fR 
Start presenting from the \fIn\fRth word. Minimum value of \fI1\fR.
.TP
.B -s \fIchars\fR
Characters used for word splitting in addition to \fB$IFS\fR. Backslash escapes are interpreted.
.TP
.B -l
Vary the speed words are presented at based on their length.
.TP
.B -q
Do not pass presentation progress to stdout if tspreed is terminated before the presentation has finished.
.TP
.B -h
Hide the cursor during the presentation.
.TP
.B -i
Display progress information during the presentation.
.TP
.B -f
Highlight the focus letter (also known as the pivot or optimal recognition point) of the word being presented.
.TP
.B -p \fIstyle\fR
Display pointers in a given style pointing towards the focus letter. Only takes effect if focus letter highlighting is enabled. Styles: \fInone\fR, \fIline\fR, \fIpoint\fR.
.TP
.B -b
Display the focus letter in bold. Only takes effect if focus letter highlighting is enabled.
.TP
.B -c \fIcolor\fR
Display the focus letter in a given color. Only takes effect if focus letter highlighting is enabled. Values are ANSI X3.64 8-bit color values, ranging from \fI0\fR to \fI255\fR.
.TP
.B -v
Print \fBtspreed\fR version and exit.

.SH CONFIGURATION
The values provided in the command options take precedence over the values provided in the local configuration file, which takes precedence over the values provided in the global configuration file.
.TP
.B wpm=\fIwpm\fR
Equivalent to the \fB-w\fR option.
.TP
.B numstart=\fInum\fR
Equivalent to the \fB-n\fR option.
.TP
.B separators=\fIchars\fR
Equivalent to the \fB-s\fR option.
.TP
.B lengthvary=\fIbool\fR
Equivalent to the \fB-l\fR option.
.TP
.B quietexit=\fIbool\fR
Equivalent to the \fB-q\fR option.
.TP
.B hidecursor=\fIbool\fR
Equivalent to the \fB-h\fR option.
.TP
.B proginfo=\fIbool\fR
Equivalent to the \fB-i\fR option.
.TP
.B focus=\fIbool\fR
Equivalent to the \fB-f\fR option.
.TP
.B focuspointer=\fIstyle\fR
Equivalent to the \fB-p\fR option.
.TP
.B focusbold=\fIbool\fR
Equivalent to the \fB-b\fR option.
.TP
.B focuscolor=\fIcolor\fR
Equivalent to the \fB-c\fR option.

.SH EXIT STATUS
.TP
.B 0
Success - presentation completed.
.TP
.B 1
Failure due to incorrect options/configuration.
.TP
.B 2
Failure due to system not supporting at least one of the required non-POSIX features or commands.
.TP
.B 3
Failure due to terminal (emulator) not supporting required capabilities.
.TP
.B 8
Presentation terminated before completion - no failure.

.SH ENVIRONMENT
.TP
.B IFS
Default characters used for word splitting.
.TP
.B XDG_CONFIG_HOME
The local configuration file is located within the directory defined. If \fB$XDG_CONFIG_HOME\fR is not set or empty, then \f(BI$HOME\fI/.config\fR is used in its place. This is in adherence to the \fIXDG Base Directory Specification\fR.

.SH FILES
.TP
.I /etc/tspreed/tspreed.rc
Global configuration file.
.TP
.I \f(BI$XDG_CONFIG_HOME\fI/tspreed/tspreed.rc
Local configuration file.

.SH EXAMPLES
.P
$ \fBtspreed < textfile\fR
.P
$ \fBpdftotext document.pdf - | tspreed -w 300 -n 120 -s '\\r\\f' -lqihfb -p line -c 1\fR

.SH PORTABILITY
\fBtspreed\fR 'officially' supports GNU-based, BSD-based, and BusyBox-based systems only due to POSIX-compliance issues described below. This does not mean the script will not work on other Unix-like systems or portability is not treated as a priority, however this does mean compatibility is not guaranteed on unsupported systems.

\fBtspreed\fR attempts to adhere to \fIIEEE Std 1003.1-2001\fR (a.k.a. \fISUSv3\fR or \fIPOSIX.1-2001\fR) in order to be portable across Unix-like systems. However, \fBthe script must utilize at least one of the below non-compliant features or commands\fR and will exit with an error if none are supported:

.TP
\fBdate\fR(1)
Can return nanoseconds via the '%N' format.
.TP
\fBsleep\fR(1)
Supports the use of fractional values for the time operand to represent units of time less than 1 second.
.TP
\fBusleep\fR(1)

.P
The script utilizes terminal capabilities via \fBtput\fR(1), but will fall back to the following where possible if those capabilities fail:

.TP
Terminal styling and cursor movement
\fIANSI X3.64\fR escape codes.
.TP
Determining terminal size
\fI$COLUMNS\fR and \fI$LINES\fR environment variables.

.SH SEE ALSO
\fBdate\fR(1), \fBsleep\fR(1), \fBterminfo\fR(5)

.SH BUGS
Bugs and issues can be reported on GitHub or GitLab.

<https://github.com/n-ivkovic/tspreed/issues>

<https://gitlab.com/n-ivkovic/tspreed/issues>

.SH AUTHORS
Nicholas Ivkovic <https://nivkovic.net>.

.SH COPYRIGHT
Copyright (c) 2021 Nicholas Ivkovic.

Licensed under the GNU General Public License version 3 or later. See ./LICENSE, or <https://gnu.org/licenses/gpl.html> if more recent, for details.

This is free software: you are free to change and redistribute it. There is NO WARRANTY, to the extent permitted by law.
