.TH tspreed 1 2023-03-11

.SH NAME
\fBtspreed\fR \- terminal RSVP speed reader with Spritz-like functionality

.SH SYNOPSIS
.B tspreed
[\fB\-lqhikfbv\fR]
[\fB\-w\fR \fIwpm\fR]
[\fB\-n\fR \fInum\fR]
[\fB\-s\fR \fIchars\fR]
[\fB\-p\fR \fIstyle\fR]
[\fB\-c\fR \fIcolor\fR]
[\fB\-K\fR \fIpath\fR]

.SH DESCRIPTION
\fBtspreed\fR is a terminal RSVP speed reader with Spritz-like functionality written in POSIX-compliant shell. The script reads plain text piped into it and presents it one word at time.

The presentation starts with the first word displayed for a minimum of 1 second, then all subsequent words are presented at the given speed (WPM).

If tspreed is terminated before the presentation has finished, the progress of the presentation is passed to stdout.

.SH OPTIONS
.TP
\fB-w\fR, \fB--wpm\fR \fIwpm\fR
Present words at the given speed in words per minute (WPM). Required to be set. Minimum value of \fI1\fR, maximum value of \fI60000\fR.
.TP
\fB-n\fR, \fB--num-start\fR \fInum\fR
Start presenting from the given \fIn\fRth word. Minimum value of \fI1\fR.
.TP
\fB-s\fR, \fB--separators\fR \fIchars\fR
Use the given characters to separate words in addition to the characters set in \fB$IFS\fR. Backslash escapes are interpreted.
.TP
\fB-l\fR, \fB--length-vary\fR
Vary the speed words are presented at based on their length.
.TP
\fB-q\fR, \fB--quiet-exit\fR
Do not output the presentation progress if tspreed is terminated before the presentation has finished.
.TP
\fB-h\fR, \fB--hide-cursor\fR
Hide the cursor during the presentation.
.TP
\fB-i\fR, \fB--progress-info\fR
Display progress information during the presentation.
.TP
\fB-k\fR, \fB--key-controls\fR
Enable keyboard controls.
.TP
\fB-f\fR, \fB--focus\fR
Highlight the focus letter (also known as the pivot or optimal recognition point) of the word being presented.
.TP
\fB-p\fR, \fB--focus-pointer\fR \fIstyle\fR
Display pointers in a given style pointing towards the focus letter. Only relevant if focus letter highlighting is enabled (\fB-f\fR/\fBfocus\fR option). Styles: \fInone\fR, \fIline\fR, \fIpoint\fR.
.TP
\fB-b\fR, \fB--focus-bold\fR
Display the focus letter in bold. Only relevant if focus letter highlighting is enabled (\fB-f\fR/\fBfocus\fR option).
.TP
\fB-c\fR, \fB--focus-color\fR \fIcolor\fR
Display the focus letter in the given color. Only relevant if focus letter highlighting is enabled (\fB-f\fR/\fBfocus\fR option). Color values are \fIANSI X3.64\fR 8-bit color values, ranging from \fI0\fR to \fI255\fR.
.TP
\fB-K\fR, \fB--dev-key-input\fR \fIpath\fR
Device/path to read keyboard input from. Only relevant if keyboard controls are enabled (\fB-k\fR/\fBkeycontrols\fR option). Defaults to \fI/dev/tty\fR.
.TP
\fB-v\fR, \fB-V\fR, \fB--version\fR
Print \fBtspreed\fR version and exit.

.SH CONFIGURATION
The values provided in the command options take precedence over the values provided in the local configuration file, which takes precedence over the values provided in the global configuration file.
.TP
.B wpm=\fIwpm\fR
Equivalent to the \fB-w\fR/\fB--wpm\fR option.
.TP
.B numstart=\fInum\fR
Equivalent to the \fB-n\fR/\fB--num-start\fR option.
.TP
.B separators=\fIchars\fR
Equivalent to the \fB-s\fR/\fB--separators\fR option.
.TP
.B lengthvary=\fIbool\fR
Equivalent to the \fB-l\fR/\fB--length-vary\fR option.
.TP
.B quietexit=\fIbool\fR
Equivalent to the \fB-q\fR/\fB--quiet-exit\fR option.
.TP
.B hidecursor=\fIbool\fR
Equivalent to the \fB-h\fR/\fB--hide-cursor\fR option.
.TP
.B proginfo=\fIbool\fR
Equivalent to the \fB-i\fR/\fB--progress-info\fR option.
.TP
.B keycontrols=\fIbool\fR
Equivalent to the \fB-k\fR/\fB--key-controls\fR option.
.TP
.B focus=\fIbool\fR
Equivalent to the \fB-f\fR/\fB--focus\fR option.
.TP
.B focuspointer=\fIstyle\fR
Equivalent to the \fB-p\fR/\fB--focus-pointer\fR option.
.TP
.B focusbold=\fIbool\fR
Equivalent to the \fB-b\fR/\fB--focus-bold\fR option.
.TP
.B focuscolor=\fIcolor\fR
Equivalent to the \fB-c\fR/\fB--focus-color\fR option.
.TP
.B devkeyinput=\fIpath\fR
Equivalent to the \fB-K\fR/\fB--dev-key-input\fR option.

.SH KEYBOARD CONTROLS

Keyboard controls can be enabled via the \fB-k\fR/\fBkeycontrols\fR option. However, not all systems and shells are able to utilise keyboard controls, see the \fBPORTABILITY - POSIX-COMPLIANCE\fR section.

.TP
.B I
Show/hide the presentation progress information.
.TP
.B P
Pause/resume the presentation. After resuming, the word that was paused on is displayed for a minimum of 0.5 seconds.
.TP
.B Q
Terminate the presentation.

.SH EXIT STATUS
.TP
.B 0
Success - presentation completed.
.TP
.B 1
Failure due to incorrect options/configuration.
.TP
.B 2
Failure due to system not supporting at least one of the required non-POSIX features or commands.
.TP
.B 3
Failure due to terminal (emulator) not supporting required capabilities.
.TP
.B 8
Success - presentation terminated before completion.

.SH ENVIRONMENT
.TP
.B IFS
Default characters used for word splitting.
.TP
.B XDG_CONFIG_HOME
The local configuration file is located within the directory defined. Uses \f(BI$HOME\fI/.config\fR if not defined in compliance with the \fIXDG Base Directory Specification\fR.

.SH FILES
.TP
.I /etc/tspreed/tspreed.rc
Global configuration file.
.TP
.I \f(BI$XDG_CONFIG_HOME\fI/tspreed/tspreed.rc
Local configuration file.

.SH EXAMPLES
.P
$ \fBtspreed < textfile\fR
.P
$ \fBtspreed --wpm 300 --hide-cursor < textfile\fR
.P
$ \fBpdftotext document.pdf - | tspreed -w 300 -n 120 -s '\\r\\f' -lqihkfb -p line -c 1 -K /dev/tty\fR

.SH PORTABILITY
\fBtspreed\fR 'officially' supports GNU-based, BSD-based, and BusyBox-based systems only due to POSIX-compliance issues described below. This does not mean the script is guaranteed to not work on other Unix-like systems or issues specific to those systems will not be addressed, merely it is unknown how well supported the script is on other Unix-like systems.

.SH PORTABILITY - POSIX-COMPLIANCE

.P
\fBtspreed\fR attempts to comply with \fIPOSIX.1-2001\fR through to \fIPOSIX.1-2008\fR in order to maintain portability across Unix-like systems. However, the script must utilize non-compliant features and commands and will exit with an error if none are supported.

.P
If keyboard controls are enabled (\fB-k\fR/\fBkeycontrols\fR option), \fIboth\fR of the below non-compliant features must be supported:

.TP
\fBdate\fR(1)
Can return nanoseconds via the '%N' format.
.TP
\fBread\fR(1)
Supports the -s option for disabling output, the -n option for limiting the number of characters read, and the -t option for specifying a timeout in fractional seconds. Bash's \fBread\fR builtin is the only major \fBread\fR(1) implementation which supports all listed non-compliant options, hence the script will likely need to be run via the Bash shell.

.P
Otherwise, \fIat least one\fR of the below non-compliant features and commands must be supported:

.TP
\fBdate\fR(1)
Can return nanoseconds via the '%N' format.
.TP
\fBsleep\fR(1)
Supports the use of fractional values for the time operand to represent units of time less than 1 second, e.g. 0.05.
.TP
\fBsleep\fR(1)
Supports the use of E notation for the time operand to represent units of time less than 1 second, e.g. 5e-2.
.TP
\fBusleep\fR(1)

.SH PORTABILITY - TERMINAL I/O

.P
The script utilizes terminal capabilities via \fBtput\fR(1), but will fall back to the following where possible if those capabilities fail:

.TP
\fIANSI X3.64\fR escape codes
For terminal styling and cursor movement.
.TP
\fB$COLUMNS\fR, \fB$LINES\fR
For determining terminal size. Will fall back to 80 columns and/or 24 lines if one or both of the environmental variables are not set.

.P
If keyboard controls are enabled (\fB-k\fR/\fBkeycontrols\fR option), keyboard input is read from \fI/dev/tty\fR by default. This can be changed via the \fB-K\fR/\fBdevkeyinput\fR option.

.SH SEE ALSO
\fBdate\fR(1), \fBsleep\fR(1), \fBusleep\fR(1), \fBterminfo\fR(5), \fBstandards\fR(7).

.SH CONFORMING TO
.TP
POSIX.1-2001, POSIX.1-2008.
.TP
ANSI X3.64.
.TP
XDG Base Directory Specification v0.6+.

.SH BUGS
Bugs and issues can be reported on GitHub or GitLab.
.TP
<https://github.com/n-ivkovic/tspreed/issues>
.TP
<https://gitlab.com/n-ivkovic/tspreed/issues>

.SH AUTHORS
Nicholas Ivkovic <https://nivkovic.net>.

.SH COPYRIGHT
Copyright (c) 2020-2023 Nicholas Ivkovic.

Licensed under the GNU General Public License version 3 or later. See ./LICENSE, or <https://gnu.org/licenses/gpl.html> if more recent, for details.

This is free software: you are free to change and redistribute it. There is NO WARRANTY, to the extent permitted by law.
